# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 71c497b6494404cd2403973229ebeaea1990a50b4477a4b49448f8e3ec4fb43457272a28ec583f55e6261a5e07ff815e415325b617e89b228f07ae0cd6759884

test:
  secret_key_base: 519edc01497acc4b72108a05e4417b6eecb520594a33c1a9a187926ad8d62e5d01b7de8291974d4aa9ef003a72f9e330f2a0586fd3d523f0792e471d22a0f130

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
